# Generated by Django 5.2.6 on 2025-09-17 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='班级名称')),
            ],
            options={
                'db_table': 'db_class',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='课程名称')),
            ],
            options={
                'db_table': 'db_course',
            },
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=11)),
                ('addr', models.CharField(max_length=22)),
            ],
            options={
                'db_table': 'db_stu_detail',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='姓名')),
                ('age', models.SmallIntegerField(default=18, verbose_name='年龄')),
                ('sex', models.SmallIntegerField(choices=[(0, '女'), (1, '男'), (2, '保密')])),
                ('clas', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='studentORM2.clas')),
                ('courses', models.ManyToManyField(db_table='db_student2coures', to='studentORM2.course')),
                ('stu_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentORM2.studentdetail')),
            ],
            options={
                'db_table': 'db_student2',
            },
        ),
    ]
