# Generated by Django 5.2.6 on 2025-09-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classmate',
            field=models.CharField(db_column='class', db_index=True, default='', max_length=5, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(default='', verbose_name='个性签名'),
        ),
    ]
