# Generated by Django 5.2.6 on 2025-09-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='chinese_socre',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='student',
            name='math_socre',
            field=models.IntegerField(default=100),
        ),
    ]
